rango/urls.py
from django.urls import path
from rango import views
app_name = 'rango'
urlpatterns = [
path('', views.index, name='index'),
path('about/', views.about, name='about'),
path('category/<slug:category_name_slug>/', views.show_category,
path('login/', views.user_login, name='login'),
path('restricted/', views.restricted, name='restricted'),
path('logout/', views.user_logout, name='logout'),
name='show_category'),
path('add_category/', views.add_category, name='add_category'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('', views.index, name='index'),
path('about/', views.about, name='about'),
path('category/<slug:category_name_slug>/add_page/', views.add_page,
name='add_page'),
path('category/<slug:category_name_slug>/', views.show_category,
name='show_category'),
path('add_category/', views.add_category, name='add_category'),
path('register/', views.register, name='register'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



rango/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
def __str__(self):
    return self.name
class Page(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
def __str__(self):
    return self.user.username
def __str__(self):
    return self.title

rango/forms.py
from django import forms
from django.contrib.auth.models import User

from rango.models import Page, Category, UserProfile


class CategoryForm(forms.ModelForm):
  name = forms.CharField(max_length=128,
  help_text="Please enter the category name.")
  views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
  slug = forms.CharField(widget=forms.HiddenInput(), required=False)

class Meta:
  model = Category
  fields = ('name',)

class PageForm(forms.ModelForm):
  title = forms.CharField(max_length=128,
  help_text="Please enter the title of the page.")
  url = forms.URLField(max_length=200,
  help_text="Please enter the URL of the page.")
  views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

class Meta:

  model = Page

  exclude = ('category',)

class UserForm(forms.ModelForm):


    password = forms.CharField(widget=forms.PasswordInput())


class Meta:
  model = User


fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
  class Meta:

      model = UserProfile


fields = ('website', 'picture',)

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse

from rango.forms import CategoryForm
from rango.models import Category
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth import authenticate, login, logout


def index(request):
    context_dict = {'boldmessage': 'Crunchy, creamy, cookie, candy, cupcake!'}
    return render(request, 'rango/index.html', context=context_dict)


def add_category(request):
    form = CategoryForm()
    if request.method == 'POST':
        form = CategoryForm(request.POST)
    if form.is_valid():
        form.save(commit=True)

        return redirect('/rango/')
    else:
        print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})


from rango.forms import PageForm


def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None
    # You cannot add a page to a Category that does not exist...
    if category is None:
        return redirect('/rango/')
    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
    if form.is_valid():
        if category:
            page = form.save(commit=False)
        page.category = category
        page.views = 0
        page.save()
        return redirect(reverse('rango:show_category',
                                kwargs={'category_name_slug':
                                            category_name_slug}))
    else:
        print(form.errors)
        context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context=context_dict)


def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

                profile.save()

                registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()
        return render(request,
              'rango/register.html',
            context={'user_form': user_form,
                    'profile_form': profile_form,
                       'registered': registered})


def user_login(request):
    if request.method == 'POST':

        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:

            if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
            else:
                return HttpResponse("Your Rango account is disabled.")
        else:
            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
    else:

        return render(request, 'rango/login.html')


@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")
@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('rango:index'))

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
  {% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" />
<br />
Password: <input type="password" name="password" value="" size="50" />
<br />
<input type="submit" value="submit" />
</form>
{% endblock %}
</div>
</body>
</html>

templates/rango/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Rango</title>
</head>
<body>

</body>
</html>

templates/rango/add_category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
 <html>
 <head>
 <title>Add a Category</title>
 </head>

 <body>
 <h1>Add a Category</h1>
 <div>
 <form id="category_form" method="post" action="/rango/add_category/">
 {% csrf_token %}
 {% for hidden in form.hidden_fields %}
 {{ hidden }}
 {% endfor %}
 {% for field in form.visible_fields %}
 {{ field.errors }}
 {{ field.help_text }}
 {{ field }}
 {% endfor %}
 <input type="submit" name="submit" value="Create Category" />
 </form>
     </div>
 </body>
 </html>

templates/rango/add_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/rango/base.html
<!DOCTYPE html>
 {% load staticfiles %}
{% load rango_template_tags %}
 <html>
 <head>
 <title>
 Rango -
 {% block title_block %}
 How to Tango with Django!
 {% endblock %}
 </title>
 </head>
 <body>
 <div>
 {% block body_block %}

{% get_category_list category %}

 {% endblock %}
 </div>
 <hr />
 <div>

 <ul>
{% if user.is_authenticated %}
<!-- Show these links when the user is logged in -->
<li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
<li><a href="{% url 'rango:logout' %}">Logout</a></li>
{% else %}
<!-- Show these links when the user is NOT logged in -->
<li><a href="{% url 'rango:register' %}">Sign Up</a></li>
<li><a href="{% url 'rango:login' %}">Login</a></li>
{% endif %}
<!-- Outside the conditional statements, ALWAYS show -->
<li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
<li><a href="{% url 'rango:about' %}">About</a></li>
<li><a href="{% url 'rango:index' %}">Index</a></li>
</ul>


 </div>

 </body>
 </html>

templates/rango/categories.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
  <ul>
 {% for c in categories %}
    {% if c == current_category %}
    <li>
<strong>
<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
</strong>
</li>
{% else %}
<li>
<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
</li>
    {% endif %}
    {% endfor %}
 {% else %}
 <li><strong>There are no categories present.</strong></li>
 {% endif %}
 </ul>

</div>
</body>
</html>

templates/rango/category.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load staticfiles %}


 <html>

 <head>
 <title>Rango</title>
 </head>

 <body>
<div>
 {% block title_block %}
 {% if category %}
 {{ category.name }}
 {% else %}
 Unknown Category
 {% endif %}
 {% endblock %}

 {% block body_block %}
 {% if category %}
 <h1>{{ category.name }}</h1>
 {% if pages %}
 <ul>
 {% for page in pages %}
 <li><a href="{{ page.url }}">{{ page.title }}</a></li>
 {% endfor %}
 </ul>
 {% else %}
 <strong>No pages currently in category.</strong>
 {% endif %}

 <a href="{% url 'rango:add_page' category.slug %}">Add Page</a> <br />
 {% else %}
 The specified category does not exist.
 {% endif %}
 {% endblock %}
 </div>
 </body>

 </html>

templates/rango/index.html
<!DOCTYPE html>
{% extends 'rango/base.html' %}
{% load static %} <!-- New line -->
<html>
<head>
<title>Homepage</title>
</head>
<body>
<h1>Rango says...</h1>
<div>
hey there partner! <br />
<strong>{{ boldmessage }}</strong><br />
</div>
<div>
    {% if categories %}
 <h2>Most Liked Categories</h2>
 <ul>
 {% for category in categories %}
 <li>{{ category.name }}</li>
     <a href="{% url 'rango:show_category' category.slug %}">
         {{ category.name }}

     </a>
 {% endfor %}
 </ul>
 {% else %}
 <strong>There are no categories present.</strong>
 {% endif %}
 </div>
<ul>
 <h2>Most Viewed Category</h2>
{% for category in categories %}
<li>
<!-- The following line is changed to add an HTML hyperlink -->
<a href="/rango/category/{{ category.slug }}/">{{ category.name }}</a>
</li>
{% endfor %}
</ul>

<a href="/rango/about/">About</a><br />
<img src="{% static 'images/rango.jpg' %}"
alt="Picture of Rango" /> <!-- New line -->
</div>
</body>
</html>

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}
{% block title_block %}
Login
{% endblock %}
{% block body_block %}
<h1>Login to Rango</h1>
<form id="login_form" method="post" action="{% url 'rango:login' %}">
{% csrf_token %}
Username: <input type="text" name="username" value="" size="50" />
<br />
Password: <input type="password" name="password" value="" size="50" />
<br />
<input type="submit" value="submit" />
</form>
{% endblock %}

templates/rango/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div>
  {% extends 'rango/base.html' %}
 {% load staticfiles %}

 {% block title_block %}
 Register
 {% endblock %}

 {% block body_block %}
 <h1>Register for Rango</h1>
 {% if registered %}
 Rango says: <strong>thank you for registering!</strong>
 <a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
 {% else %}
 Rango says: <strong>register here!</strong><br />
 <form id="user_form" method="post" action="{% url 'rango:register' %}"
 enctype="multipart/form-data">

 {% csrf_token %}

 {{ user_form.as_p }}
 {{ profile_form.as_p }}

 <input type="submit" name="submit" value="Register" />
 </form>
 {% endif %}
 {% endblock %}
</div>

</body>
</html>